baseURL = "https://onmyownti.me"
languageCode = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title = "onmyownti.me"
theme = ["omot-theme", "hugo-shortcode-gallery"]
googleAnalytics = "UA-153610523-1"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
timeout = 3600000

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    homepage = "main"

[[params.mainMenu]]
	link = "/dialog"
	text = "dialog"

[[params.mainMenu]]
	link = "/photos"
	text = "photos"

[[params.mainMenu]]
    link = "/me"
    text = "me"
