baseURL = "https://template.onmyownti.me"
languageCode = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title = "onmyownti.me"
theme = ["omot-theme"]
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
timeout = 3600000

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    homepage = "main"
    main_title = "stuff you do on your own time"

[[params.mainMenu]]
	link = "/blog"
	text = "blog"

[[params.mainMenu]]
	link = "/photos"
	text = "photos"

[[params.mainMenu]]
    link = "/me"
    text = "me"
